apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-robot-v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-example-eventlistener-binding-v1alpha1
subjects:
  - kind: ServiceAccount
    name: tekton-robot-v1alpha1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles-v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-example-eventlistener-clusterbinding-v1alpha1
subjects:
  - kind: ServiceAccount
    name: tekton-robot-v1alpha1
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles-v1alpha1