apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: hello-goodbyev1
spec:
  params:
    - name: username
      type: string
  tasks:
    - name: hello
      taskRef:
        name: hellov1
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbyev1
      params:
        - name: username
          value: $(params.username)