apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbyev1beta1
spec:
  params:
    - name: username
      type: string
  tasks:
    - name: hello
      taskRef:
        name: hellov1beta1
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbyev1beta1
      params:
        - name: username
          value: $(params.username)