apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: goodbyev1
spec:
  params:
    - name: username
      type: string
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"  
